"""
Integration tests for the Doc Maker integration.

No API key required — doc-maker is pure local compute (python-docx).
These tests exercise real document generation through the action handlers.

Run with:
    pytest doc-maker/tests/test_doc_maker_integration.py -m integration
"""

import os
import sys
import importlib
import importlib.util
import base64

_parent = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_deps = os.path.abspath(os.path.join(os.path.dirname(__file__), "../dependencies"))
sys.path.insert(0, _parent)
sys.path.insert(0, _deps)

import pytest  # noqa: E402
from unittest.mock import AsyncMock, MagicMock  # noqa: E402
from autohive_integrations_sdk.integration import ResultType  # noqa: E402

_original_cwd = os.getcwd()
os.chdir(_parent)
_spec = importlib.util.spec_from_file_location("doc_maker_mod_intg", os.path.join(_parent, "doc_maker.py"))
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
os.chdir(_original_cwd)
sys.modules["doc_maker_mod_intg"] = _mod

doc_maker = _mod.doc_maker

pytestmark = pytest.mark.integration


@pytest.fixture
def live_context():
    ctx = MagicMock(name="ExecutionContext")
    ctx.fetch = AsyncMock(name="fetch")
    ctx.auth = {}
    return ctx


class TestCreateDocument:
    async def test_creates_blank_document(self, live_context):
        result = await doc_maker.execute_action("create_document", {}, live_context)

        assert result.type == ResultType.ACTION
        data = result.result.data
        assert "document_id" in data
        assert isinstance(data["document_id"], str)
        assert len(data["document_id"]) > 0
        assert data["saved"] is True

    async def test_create_document_returns_valid_docx_binary(self, live_context):
        result = await doc_maker.execute_action("create_document", {}, live_context)

        data = result.result.data
        assert "file" in data
        file_obj = data["file"]
        assert "content" in file_obj
        assert file_obj["name"].endswith(".docx")

        # Verify the content is valid base64-encoded DOCX (ZIP magic bytes PK)
        raw = base64.b64decode(file_obj["content"] + "==")
        assert raw[:2] == b"PK"

    async def test_create_document_with_title(self, live_context):
        result = await doc_maker.execute_action("create_document", {"title": "My Integration Test Doc"}, live_context)

        assert result.type == ResultType.ACTION
        data = result.result.data
        assert data["saved"] is True
        assert data["paragraph_count"] >= 1

    async def test_create_document_with_markdown_content(self, live_context):
        markdown = "# Test Heading\n\nThis is a **bold** paragraph.\n\n- Item one\n- Item two"
        result = await doc_maker.execute_action("create_document", {"markdown_content": markdown}, live_context)

        assert result.type == ResultType.ACTION
        data = result.result.data
        assert data["saved"] is True
        assert data["markdown_processed"] is True


class TestAddTable:
    async def test_add_table_to_document(self, live_context):
        create_result = await doc_maker.execute_action("create_document", {}, live_context)
        document_id = create_result.result.data["document_id"]

        file_obj = create_result.result.data["file"]

        result = await doc_maker.execute_action(
            "add_table",
            {
                "document_id": document_id,
                "rows": 2,
                "cols": 3,
                "data": [["Name", "Age", "City"], ["Alice", "30", "Auckland"]],
                "files": [file_obj],
            },
            live_context,
        )

        assert result.type == ResultType.ACTION
        data = result.result.data
        assert data["saved"] is True
        assert data["table_rows"] == 2
        assert data["table_cols"] == 3


class TestSaveDocument:
    async def test_save_document_returns_valid_docx(self, live_context):
        create_result = await doc_maker.execute_action(
            "create_document",
            {"markdown_content": "# Integration Test\n\nGenerated by doc-maker integration tests."},
            live_context,
        )
        document_id = create_result.result.data["document_id"]
        file_obj = create_result.result.data["file"]

        save_result = await doc_maker.execute_action(
            "save_document",
            {
                "document_id": document_id,
                "file_path": "output.docx",
                "files": [file_obj],
            },
            live_context,
        )

        assert save_result.type == ResultType.ACTION
        data = save_result.result.data
        assert data["saved"] is True
        assert "file" in data
        assert data["file"]["name"].endswith(".docx")

        raw = base64.b64decode(data["file"]["content"] + "==")
        assert raw[:2] == b"PK"

    async def test_save_missing_document_returns_error(self, live_context):
        result = await doc_maker.execute_action(
            "save_document",
            {"document_id": "nonexistent-doc-id-12345", "file_path": "output.docx"},
            live_context,
        )

        assert result.type == ResultType.ACTION_ERROR
        assert "nonexistent-doc-id-12345" in result.result.message


class TestAddMarkdownContent:
    async def test_add_markdown_to_existing_document(self, live_context):
        create_result = await doc_maker.execute_action("create_document", {}, live_context)
        document_id = create_result.result.data["document_id"]
        file_obj = create_result.result.data["file"]

        result = await doc_maker.execute_action(
            "add_markdown_content",
            {
                "document_id": document_id,
                "markdown_content": "## Section Added Later\n\nThis content was appended.",
                "files": [file_obj],
            },
            live_context,
        )

        assert result.type == ResultType.ACTION
        assert result.result.data["saved"] is True
