name: Validate Integration (Tooling)

on:
  pull_request:
    branches: [master, main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Integration
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate
        uses: autohive-ai/autohive-integrations-tooling@1.0.3
        with:
          base_ref: origin/${{ github.base_ref }}
